name: 'minecraft-whitelist-validator'
description: 'validate Minecraft whitelist.json'
author: 'sksat <sksat@sksat.net>'

inputs:
  json:
    description: whitelist.json
    required: true
    default: 'whitelist.json'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/sksat/minecraft-whitelist-validator:develop'
  args:
    - ${{ inputs.json }}
