name: Build single-binary

on:
  push:
    branches:
      - main

jobs:
  build-single:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target x86_64-unknown-linux-musl
    - uses: actions/upload-artifact@v2
      with:
        name: minecraft-whitelist-validator
        path: target/x86_64-unknown-linux-musl/release/minecraft-whitelist-validator
