name: build / single-binary by musl libc

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-single:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-musl

    - name: build
      run: |
        cargo build --release --target x86_64-unknown-linux-musl

    - uses: actions/upload-artifact@v4.3.4
      with:
        name: minecraft-whitelist-validator
        path: target/x86_64-unknown-linux-musl/release/minecraft-whitelist-validator
