name: build / single-binary by musl libc

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-single:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target x86_64-unknown-linux-musl
    - uses: actions/upload-artifact@v3
      with:
        name: minecraft-whitelist-validator
        path: target/x86_64-unknown-linux-musl/release/minecraft-whitelist-validator
